name: Test & Build workflow

on:
  - push

jobs:
  npm-dependency-check-unused-packages:
    name: Check Unused dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: packages check
        uses: Amr-Reda/npm-unused-packages-checker@v1
        with:
          IGNORE_PACKAGES: '["jade"]'
          IGNORE_PATTERNS: '["*.json"]'
  npm-dependency-check-new-packages:
    name: Check new dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check for new dependencies
        uses: hiwelo/new-dependencies-action@1.0.1
  run-Eslint-quality-check:
    name: Run NPM eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run NPM eslint
        uses: anna-money/github-actions-npm@v1
