name: Feature / Develop branch workflow

on:
  push:
    branches:
      - 'feature/**'
      - develop

jobs:
  standard_code_analysis:
    name: Standard code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check Unused dependencies
        if: github.ref != 'refs/heads/develop'
        uses: Amr-Reda/npm-unused-packages-checker@v1
        with:
          IGNORE_PACKAGES: '["jade"]'
          IGNORE_PATTERNS: '["*.json"]'
      - name: NPM Install (node_modules installation)
        run: npm install
      - name: Run Prettier check for code formatting
        if: github.ref != 'refs/heads/develop'
        run: ./node_modules/.bin/prettier --write ./
      #TODO Need to add condition check for pull request, else commenting it out
      # - name: Create Pull Request for prettier
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     token: ${{ secrets.PAT }}
      #     commit-message: Update report
      #     committer: GitHub <noreply@github.com>
      #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      #     signoff: false
      #     branch: example-patches
      #     delete-branch: true
      #     title: 'Formatting Code using Prettier'
      #     body: |
      #       Formatted the files using Prettier,
      #       that aren't formatted yet.
      #     labels: |
      #       report
      #       automated pr
      #     assignees: peter-evans
      #     reviewers: peter-evans
      - name: Run ESLint
        run: |
          ./node_modules/.bin/eslint src/ --ext .js,.jsx,.ts,.tsx
      - name: Generate Build artefacts
        working-directory: ${{ github.workspace }}
        run: npm run build
      - name: Run Unit test
        working-directory: ${{ github.workspace }}
        run: npm run test -- --coverage --watchAll=false
