name: Feature / Develop /Pull Request workflow

on:
  push:
    branches:
      - 'feature/**'
      - develop
  pull_request:
    types: [opened, reopened]

jobs:
  standard_code_analysis:
    name: Standard code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check Unused dependencies
        if: ${{ github.event_name != 'pull_request' }}
        uses: Amr-Reda/npm-unused-packages-checker@v1
        with:
          IGNORE_PACKAGES: '["jade"]'
          IGNORE_PATTERNS: '["*.json"]'
      - name: Run Eslint
        uses: getsentry/action-eslint-fix@v1
        with:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
          dry: true
      - name: Run Prettier check for code formatting
        if: ${{ github.event_name != 'pull_request' }}
        uses: creyD/prettier_action@v2.2
  run_unit_testing_and_build_artefacts:
    name: Install node_modules & Run unit test scripts and generate coverge report
    runs-on: ubuntu-latest
    needs: standard_code_analysis
    steps:
      - uses: actions/checkout@master
      - name: Install node_modules & Run Unit test & Build artefacts
        working-directory: ${{ github.workspace }}
        run: |
          node -v
          npm -v
          npm install
          npm run test -- --coverage --watchAll=false
          npm run build
