name: Nightly Builder Job workflow

on:
  push:
    branches: 
      - ignore
#   schedule:
#     - cron: '0 20 * * 1-6'
#     # cron job runs on basis of GMT time

jobs:
  run-unit-testing-and-build-artefacts:
    name: Install node_modules & Run unit test scripts and generate coverge report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node_modules & Run Unit test & Build artefacts
        working-directory: ${{ github.workspace }}
        run: |
          node -v
          npm -v
          npm install
          npm run test -- --coverage --watchAll=false
          npm run build
  build-deploy-to-heroku:
    name: 'Heroku build and deploy'
    runs-on: ubuntu-latest
    env:
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
    needs: run-unit-testing-and-build-artefacts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy files
        run: cp -r /home/runner/work/$HEROKU_APP_NAME-sample/$HEROKU_APP_NAME-sample/** /home/runner
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0
        with:
          email: $HEROKU_EMAIL
          api_key: $HEROKU_API_KEY
          app_name: $HEROKU_APP_NAME
          dockerfile_path: /home/runner/work/$HEROKU_APP_NAME-sample/$HEROKU_APP_NAME-sample
  cypress-run:
    name: Cypress testing
    runs-on: ubuntu-16.04
    needs: build-deploy-to-heroku
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
