name: Pull Request workflow

on:
  pull_request:
    types: [opened, reopened]

jobs:
  standard_code_analysis:
    name: Standard code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install and Run ESLint
        run: |
          npm i eslint
          ./node_modules/.bin/eslint src/ --ext .js,.jsx,.ts,.tsx
  run_unit_testing_and_build_artefacts:
    name: Install node_modules & Run unit test scripts and generate coverge report
    runs-on: ubuntu-latest
    needs: standard_code_analysis
    steps:
      - uses: actions/checkout@master
      - name: Install node_modules & Run Unit test & Build artefacts
        working-directory: ${{ github.workspace }}
        run: |
          node -v
          npm -v
          npm install
          npm run test -- --coverage --watchAll=false
          npm run build
