name: Pull Request workflow

on:
  pull_request:
    types: [opened, reopened]

jobs:
  standard_code_analysis:
    name: Standard code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: NPM Install (node_modules installation)
        run: npm i
      - name: Run ESLint
        run: |
          ./node_modules/.bin/eslint src/ --ext .js,.jsx,.ts,.tsx
      - name: Run Unit test & Build artefacts
        working-directory: ${{ github.workspace }}
        run: |
          npm install
          npm run test -- --coverage --watchAll=false
          npm run build
