name: Test & Build workflow

on:
  push:
    branches:
      - master
      - release

defaults:
  run:
    working-directory: /github/workspace

jobs:
  # run-unit-testing-and-build-artefacts:
  #   name: Install node_modules & Run unit test scripts and generate coverge report
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Install node_modules & Run Unit test & Build artefacts
  #       working-directory: ${{ github.workspace }}
  #       run: |
  #         node -v
  #         npm -v
  #         npm install
  #         npm run test -- --coverage --watchAll=false
  #         npm run build
  sonarQubeTrigger:
    name: Quality gate - SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Generate unit-test coverage folder
        run: |
          npm install
          npm run test -- --coverage --watchAll=false
          pwd
          cat coverage/lcov.info
          rm -rf node_modules
          ls -lRt
          pwd
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@master
        with:
          host: ${{ secrets.SONAR_HOST }}
          login: ${{ secrets.SONAR_TOKEN }}
  # cypress-run:
  #   name: Cypress testing
  #   runs-on: ubuntu-16.04
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: cypress-io/github-action@v2
  #       with:
  #         browser: chrome
  #         headless: true
